<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><Optimize>true</Optimize>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="*.cs" />
    <Compile Include="../patch_time_logger/PeResources.cs" Link="PeResources.cs" />
    <Reference Include="PatchFrameProfile"><HintPath>$(FrameToolPath)</HintPath></Reference>
    <Reference Include="Mono.Cecil"><HintPath>$(CecilPath)</HintPath></Reference>
  </ItemGroup>
  <Target Name="ValidateCecilPath" BeforeTargets="ResolveReferences">
    <Error Condition="'$(CecilPath)' == '' or !Exists('$(CecilPath)')" Text="Provide target SDK CecilPath" />
  </Target>
</Project>
