FROM localhost/monobuild:local
RUN apt-get update && apt-get install -y --no-install-recommends python3-pip python3-mako bison flex pkg-config && rm -rf /var/lib/apt/lists/* && pip3 install --break-system-packages meson==0.59.4
