<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>NxCrypto</AssemblyName>
    <RootNamespace>Terraria.NxCrypto</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup><Compile Include="NxCrypto.cs" /></ItemGroup>
</Project>
