using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Mono.Cecil;
using Mono.Cecil.Cil;
using static Contracts;

internal static class AuditCanonical
{
 internal static string Json(object? o)=>JsonSerializer.Serialize(o,new JsonSerializerOptions{NumberHandling=System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals});
 internal static object[] Attrs(ICustomAttributeProvider p)=>p.CustomAttributes.Select(a=>(object)new{ctor=a.Constructor.FullName,blob=Convert.ToHexString(a.GetBlob())}).ToArray();
 internal static object[] Security(ISecurityDeclarationProvider p)=>p.SecurityDeclarations.Select(s=>(object)new{action=s.Action,blob=Convert.ToHexString(s.GetBlob())}).ToArray();
 internal static object[] Generic(IGenericParameterProvider p)=>p.GenericParameters.Select(g=>(object)new{g.Name,g.Attributes,attrs=Attrs(g),constraints=g.Constraints.Select(c=>new{type=c.ConstraintType.FullName,attrs=Attrs(c)})}).ToArray();
 internal static object? Marshal(IMarshalInfoProvider p)=>p.HasMarshalInfo?new{kind=p.MarshalInfo.GetType().FullName,data=Json(p.MarshalInfo)}:null;
 internal static object Parameter(ParameterDefinition p)=>new{p.Name,p.Attributes,type=p.ParameterType.FullName,p.HasConstant,p.Constant,marshal=Marshal(p),attrs=Attrs(p)};
 internal static object Signature(MethodDefinition m)=>new{m.Name,m.Attributes,m.ImplAttributes,m.HasThis,m.ExplicitThis,m.CallingConvention,result=new{type=m.ReturnType.FullName,m.MethodReturnType.Attributes,m.MethodReturnType.HasConstant,m.MethodReturnType.Constant,marshal=Marshal(m.MethodReturnType),attrs=Attrs(m.MethodReturnType)},parameters=m.Parameters.Select(Parameter),generic=Generic(m),attrs=Attrs(m),security=Security(m),overrides=m.Overrides.Select(o=>o.FullName),pinvoke=m.HasPInvokeInfo?new{m.PInvokeInfo.Attributes,m.PInvokeInfo.EntryPoint,module=m.PInvokeInfo.Module.Name}:null};
 internal static string Op(Instruction i)=>i.OpCode.OperandType==OperandType.ShortInlineBrTarget?i.OpCode.Name[..^2]:i.OpCode.Name;
 internal static string Operand(MethodDefinition m,object? value)=>value switch {null=>"",Instruction t=>"i"+m.Body.Instructions.IndexOf(t),Instruction[] ts=>string.Join(",",ts.Select(t=>"i"+m.Body.Instructions.IndexOf(t))),MemberReference member=>member.FullName,VariableDefinition v=>"v"+v.Index,ParameterDefinition p=>"p"+p.Index,CallSite call=>call.FullName,byte[] b=>Convert.ToHexString(b),_=>Convert.ToString(value,CultureInfo.InvariantCulture)??""};
 internal static string Body(MethodDefinition m)=>!m.HasBody?"":Json(new{m.Body.InitLocals,variables=m.Body.Variables.Select(v=>v.VariableType.FullName),instructions=m.Body.Instructions.Select(i=>new{op=Op(i),operand=Operand(m,i.Operand)}),handlers=m.Body.ExceptionHandlers.Select(h=>new{h.HandlerType,catchType=h.CatchType?.FullName,ts=Operand(m,h.TryStart),te=Operand(m,h.TryEnd),hs=Operand(m,h.HandlerStart),he=Operand(m,h.HandlerEnd),fs=Operand(m,h.FilterStart)})});
 internal static string TypeMeta(TypeDefinition t)=>Json(new{t.Namespace,t.Name,t.Attributes,baseType=t.BaseType?.FullName,t.PackingSize,t.ClassSize,attrs=Attrs(t),security=Security(t),generic=Generic(t),interfaces=t.Interfaces.Select(i=>new{type=i.InterfaceType.FullName,attrs=Attrs(i)}),nested=t.NestedTypes.Select(n=>n.FullName),fields=t.Fields.Select(f=>new{f.Name,type=f.FieldType.FullName,f.Attributes,f.HasConstant,f.Constant,f.Offset,initial=Convert.ToHexString(f.InitialValue),marshal=Marshal(f),attrs=Attrs(f)}),properties=t.Properties.Select(p=>new{p.Name,p.Attributes,type=p.PropertyType.FullName,p.HasConstant,p.Constant,parameters=p.Parameters.Select(Parameter),get=p.GetMethod?.FullName,set=p.SetMethod?.FullName,other=p.OtherMethods.Select(m=>m.FullName),attrs=Attrs(p)}),events=t.Events.Select(e=>new{e.Name,e.Attributes,type=e.EventType.FullName,add=e.AddMethod?.FullName,remove=e.RemoveMethod?.FullName,invoke=e.InvokeMethod?.FullName,other=e.OtherMethods.Select(m=>m.FullName),attrs=Attrs(e)})});
 internal static string ModuleMeta(AssemblyDefinition a)=>Json(new{assembly=a.Name.FullName,attrs=Attrs(a),security=Security(a),a.MainModule.Kind,a.MainModule.RuntimeVersion,a.MainModule.Architecture,a.MainModule.Attributes,a.MainModule.Characteristics,a.MainModule.Name,a.MainModule.MetadataKind,entry=a.EntryPoint?.FullName,moduleAttrs=Attrs(a.MainModule),references=a.MainModule.AssemblyReferences.Select(r=>r.FullName),moduleReferences=a.MainModule.ModuleReferences.Select(r=>r.Name),resources=a.MainModule.Resources.Select(r=>new{r.Name,r.Attributes,r.ResourceType,data=r is EmbeddedResource e?Sha(e.GetResourceData()):r is LinkedResource l?l.File:r is AssemblyLinkedResource ar?ar.Assembly.FullName:"unknown"}),exported=a.MainModule.ExportedTypes.Select(t=>new{t.FullName,t.Attributes,scope=t.Scope.Name})});
 internal static bool Local0(Instruction i)=>i.OpCode==OpCodes.Ldloc_0 || i.OpCode.Code is Code.Ldloc or Code.Ldloc_S && i.Operand is VariableDefinition v && v.Index==0;
}
